import { ThemeConfig, ThemeMode } from '../types';

type ThemeColors = {
  background: string;
  backgroundAlt: string;
  surface: string;
  surfaceStrong: string;
  text: string;
  textMuted: string;
  textSubtle: string;
  accent: string;
  accentStrong: string;
  accentContrast: string;
  border: string;
  borderStrong: string;
  heroStart: string;
  heroMid: string;
  heroEnd: string;
  glow: string;
  success: string;
  warning: string;
  danger: string;
};

export type ThemePreset = {
  id: ThemeMode;
  name: string;
  shortName: string;
  emoji: string;
  family: 'light' | 'dark';
  colors: ThemeColors;
};

export const DEFAULT_THEME_MODE: ThemeMode = 'day';

export const THEME_PRESETS: Record<ThemeMode, ThemePreset> = {
  day: {
    id: 'day',
    name: 'Dia',
    shortName: 'Dia',
    emoji: '☀️',
    family: 'light',
    colors: {
      background: '#fefefe',
      backgroundAlt: '#f8f9fa',
      surface: '#ffffff',
      surfaceStrong: '#e9ecef',
      text: '#1a1a2e',
      textMuted: '#495057',
      textSubtle: '#6c757d',
      accent: '#6366f1',
      accentStrong: '#4f46e5',
      accentContrast: '#ffffff',
      border: '#dee2e6',
      borderStrong: '#ced4da',
      heroStart: '#6366f1',
      heroMid: '#e0e7ff',
      heroEnd: '#f8f9fa',
      glow: '#818cf8',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  dusk: {
    id: 'dusk',
    name: 'Entardecer',
    shortName: 'Tarde',
    emoji: '🌅',
    family: 'light',
    colors: {
      background: '#fff7ed',
      backgroundAlt: '#ffedd5',
      surface: '#ffffff',
      surfaceStrong: '#fed7aa',
      text: '#1c1917',
      textMuted: '#57534e',
      textSubtle: '#78716c',
      accent: '#f97316',
      accentStrong: '#ea580c',
      accentContrast: '#ffffff',
      border: '#fed7aa',
      borderStrong: '#fdba74',
      heroStart: '#fb923c',
      heroMid: '#ffedd5',
      heroEnd: '#fff7ed',
      glow: '#fdba74',
      success: '#22c55e',
      warning: '#eab308',
      danger: '#dc2626',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Oceano',
    shortName: 'Oceano',
    emoji: '🌊',
    family: 'light',
    colors: {
      background: '#f0f9ff',
      backgroundAlt: '#e0f2fe',
      surface: '#ffffff',
      surfaceStrong: '#bae6fd',
      text: '#0c4a6e',
      textMuted: '#0369a1',
      textSubtle: '#0ea5e9',
      accent: '#0ea5e9',
      accentStrong: '#0284c7',
      accentContrast: '#ffffff',
      border: '#bae6fd',
      borderStrong: '#7dd3fc',
      heroStart: '#38bdf8',
      heroMid: '#e0f2fe',
      heroEnd: '#f0f9ff',
      glow: '#7dd3fc',
      success: '#14b8a6',
      warning: '#f59e0b',
      danger: '#f43f5e',
    },
  },
  forest: {
    id: 'forest',
    name: 'Bosque',
    shortName: 'Bosque',
    emoji: '🌲',
    family: 'light',
    colors: {
      background: '#f0fdf4',
      backgroundAlt: '#dcfce7',
      surface: '#ffffff',
      surfaceStrong: '#bbf7d0',
      text: '#14532d',
      textMuted: '#166534',
      textSubtle: '#22c55e',
      accent: '#22c55e',
      accentStrong: '#16a34a',
      accentContrast: '#ffffff',
      border: '#bbf7d0',
      borderStrong: '#86efac',
      heroStart: '#4ade80',
      heroMid: '#dcfce7',
      heroEnd: '#f0fdf4',
      glow: '#86efac',
      success: '#22c55e',
      warning: '#eab308',
      danger: '#dc2626',
    },
  },
  rose: {
    id: 'rose',
    name: 'Aurora',
    shortName: 'Aurora',
    emoji: '🌸',
    family: 'light',
    colors: {
      background: '#fdf2f8',
      backgroundAlt: '#fce7f3',
      surface: '#ffffff',
      surfaceStrong: '#fbcfe8',
      text: '#831843',
      textMuted: '#9d174d',
      textSubtle: '#db2777',
      accent: '#ec4899',
      accentStrong: '#db2777',
      accentContrast: '#ffffff',
      border: '#fbcfe8',
      borderStrong: '#f9a8d4',
      heroStart: '#f472b6',
      heroMid: '#fce7f3',
      heroEnd: '#fdf2f8',
      glow: '#f9a8d4',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  violet: {
    id: 'violet',
    name: 'Lavanda',
    shortName: 'Lavanda',
    emoji: '💜',
    family: 'light',
    colors: {
      background: '#faf5ff',
      backgroundAlt: '#f3e8ff',
      surface: '#ffffff',
      surfaceStrong: '#ede9fe',
      text: '#4c1d95',
      textMuted: '#6b21a8',
      textSubtle: '#9333ea',
      accent: '#9333ea',
      accentStrong: '#7e22ce',
      accentContrast: '#ffffff',
      border: '#ede9fe',
      borderStrong: '#d8b4fe',
      heroStart: '#a855f7',
      heroMid: '#f3e8ff',
      heroEnd: '#faf5ff',
      glow: '#d8b4fe',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ec4899',
    },
  },
  night: {
    id: 'night',
    name: 'Noite',
    shortName: 'Noite',
    emoji: '🌙',
    family: 'dark',
    colors: {
      background: '#09090b',
      backgroundAlt: '#18181b',
      surface: '#27272a',
      surfaceStrong: '#3f3f46',
      text: '#fafafa',
      textMuted: '#a1a1aa',
      textSubtle: '#71717a',
      accent: '#6366f1',
      accentStrong: '#818cf8',
      accentContrast: '#ffffff',
      border: '#3f3f46',
      borderStrong: '#52525b',
      heroStart: '#6366f1',
      heroMid: '#27272a',
      heroEnd: '#09090b',
      glow: '#818cf8',
      success: '#34d399',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  ember: {
    id: 'ember',
    name: 'Brasa',
    shortName: 'Brasa',
    emoji: '🔥',
    family: 'dark',
    colors: {
      background: '#1c0a0a',
      backgroundAlt: '#2a0f0f',
      surface: '#3d1515',
      surfaceStrong: '#4a1a1a',
      text: '#fef2f2',
      textMuted: '#fca5a5',
      textSubtle: '#f87171',
      accent: '#ef4444',
      accentStrong: '#f87171',
      accentContrast: '#ffffff',
      border: '#4a1a1a',
      borderStrong: '#7f1d1d',
      heroStart: '#dc2626',
      heroMid: '#2a0f0f',
      heroEnd: '#1c0a0a',
      glow: '#f87171',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  abyss: {
    id: 'abyss',
    name: 'Abismo',
    shortName: 'Abismo',
    emoji: '🌌',
    family: 'dark',
    colors: {
      background: '#030712',
      backgroundAlt: '#111827',
      surface: '#1f2937',
      surfaceStrong: '#374151',
      text: '#f9fafb',
      textMuted: '#9ca3af',
      textSubtle: '#6b7280',
      accent: '#3b82f6',
      accentStrong: '#60a5fa',
      accentContrast: '#ffffff',
      border: '#374151',
      borderStrong: '#4b5563',
      heroStart: '#2563eb',
      heroMid: '#111827',
      heroEnd: '#030712',
      glow: '#60a5fa',
      success: '#34d399',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  emerald: {
    id: 'emerald',
    name: 'Esmeralda',
    shortName: 'Esmeralda',
    emoji: '💎',
    family: 'dark',
    colors: {
      background: '#022c22',
      backgroundAlt: '#064e3b',
      surface: '#065f46',
      surfaceStrong: '#047857',
      text: '#ecfdf5',
      textMuted: '#6ee7b7',
      textSubtle: '#34d399',
      accent: '#10b981',
      accentStrong: '#34d399',
      accentContrast: '#022c22',
      border: '#047857',
      borderStrong: '#059669',
      heroStart: '#059669',
      heroMid: '#064e3b',
      heroEnd: '#022c22',
      glow: '#10b981',
      success: '#34d399',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    shortName: 'Neon',
    emoji: '💫',
    family: 'dark',
    colors: {
      background: '#0f0314',
      backgroundAlt: '#1a0524',
      surface: '#2a0a3a',
      surfaceStrong: '#3d1254',
      text: '#f0abfc',
      textMuted: '#c084fc',
      textSubtle: '#a855f7',
      accent: '#d946ef',
      accentStrong: '#e879f9',
      accentContrast: '#0f0314',
      border: '#3d1254',
      borderStrong: '#7c3aed',
      heroStart: '#d946ef',
      heroMid: '#1a0524',
      heroEnd: '#0f0314',
      glow: '#e879f9',
      success: '#22d3ee',
      warning: '#facc15',
      danger: '#fb7185',
    },
  },
  frost: {
    id: 'frost',
    name: 'Gelo',
    shortName: 'Gelo',
    emoji: '❄️',
    family: 'dark',
    colors: {
      background: '#082044',
      backgroundAlt: '#0f2d52',
      surface: '#0c345a',
      surfaceStrong: '#0a2540',
      text: '#e0f2fe',
      textMuted: '#7dd3fc',
      textSubtle: '#38bdf8',
      accent: '#38bdf8',
      accentStrong: '#0ea5e9',
      accentContrast: '#082044',
      border: '#155e75',
      borderStrong: '#0891b2',
      heroStart: '#0ea5e9',
      heroMid: '#0f2d52',
      heroEnd: '#082044',
      glow: '#38bdf8',
      success: '#22d3ee',
      warning: '#fde047',
      danger: '#fb923c',
    },
  },
};

export const THEME_OPTIONS = Object.values(THEME_PRESETS);
export const THEME_CLASSNAMES = THEME_OPTIONS.map((theme) => theme.id);

export const getThemePreset = (mode: ThemeMode) => THEME_PRESETS[mode] ?? THEME_PRESETS[DEFAULT_THEME_MODE];

export const normalizeThemeMode = (mode: string | undefined): ThemeMode => {
  if (!mode) return DEFAULT_THEME_MODE;
  const validModes = THEME_CLASSNAMES;
  if (validModes.includes(mode as ThemeMode)) {
    return mode as ThemeMode;
  }
  const map: Record<string, ThemeMode> = {
    light: 'day',
    dark: 'night',
    eclipse: 'abyss',
    sepia: 'dusk',
  };
  return map[mode] || DEFAULT_THEME_MODE;
};

export const getThemeVariables = (config: ThemeConfig) => {
  const preset = getThemePreset(config.mode);
  return {
    '--background-bible': preset.colors.background,
    '--background-alt-bible': preset.colors.backgroundAlt,
    '--surface-bible': preset.colors.surface,
    '--surface-hover': preset.colors.surfaceStrong,
    '--text-bible': preset.colors.text,
    '--text-muted-bible': preset.colors.textMuted,
    '--text-subtle-bible': preset.colors.textSubtle,
    '--accent-bible': preset.colors.accent,
    '--accent-strong-bible': preset.colors.accentStrong,
    '--accent-contrast-bible': preset.colors.accentContrast,
    '--border-bible': preset.colors.border,
    '--border-strong-bible': preset.colors.borderStrong,
    '--accent-bible-rgb': preset.colors.accent.replace('#', ''),
    '--accent-bible-alpha': preset.colors.accent + '40',
    '--surface-rgb': preset.colors.surface.replace('#', ''),
    '--hero-start-bible': preset.colors.heroStart,
    '--hero-mid-bible': preset.colors.heroMid,
    '--hero-end-bible': preset.colors.heroEnd,
    '--glow-bible': preset.colors.glow,
    '--success-bible': preset.colors.success,
    '--warning-bible': preset.colors.warning,
    '--danger-bible': preset.colors.danger,
    '--font-bible-family': config.fontFamily === 'Untitled Serif' ? '"Libre Baskerville", serif' : config.fontFamily,
    '--font-bible-size': `${config.fontSize}px`,
    '--font-bible-line-height': config.lineHeight.toString(),
    '--font-bible-letter-spacing': `${config.letterSpacing}em`,
    '--horizontal-margin': `${config.horizontalMargin}px`,
  };
};